# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AIVimo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AIVimo
  pod 'Reachability'

#pod 'FacebookLogin' , '~> 0.3'
#pod 'XCGLogger', '~> 6.0'
pod 'MBProgressHUD'
pod 'IQKeyboardManagerSwift', '5.0.0'
#pod 'SVPullToRefresh', '0.4.1'
#pod 'FloatRatingView'#, '~> 2.0.0'
#pod 'Toast-Swift'#, '~> 2.0.0'
#pod 'UIFloatLabelTextField'

#
# Maps and Google Place API
#
#pod 'GoogleMaps', '~> 2.6'
#pod 'GooglePlaces'

#
# Lean & Crash Analytics
#
#pod 'Firebase/Core'
pod 'Fabric', '~> 1.7.6'
pod 'Crashlytics', '~> 3.10.1'


  target 'AIVimoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AIVimoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
